# E2E Webshop Runtime Matrix
base.url=https://demowebshop.tricentis.com
browser=chrome
default.timeout.seconds=15

# Target Identity Provisioning
login.username=qa.user123@mailinator.com
login.password=Engineer@09876
